version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_database:/data/db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_database:

networks:
  app-network:
    driver: bridge 