name: Terraform CI/CD with Checkov Manual Apply

on:
  push:
    branches:
      - checkov

permissions:
  issues: write

jobs:
  # Estágio 1: Análise de Segurança com Checkov
  security-scan:
    name: Security Scan with Checkov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true
        with:
          directory: terraform-checkov
          framework: terraform
          soft_fail: true
          output_format: cli

  # Estágio 2: Terraform Plan
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: security-scan
    defaults:
      run:
        working-directory: terraform-checkov

    steps:
      - uses: actions/checkout@v2

      - name: skip-workflow
      
        id: skip-workflow # id used for referencing step
        
        uses: saulmaldonado/skip-workflow@v1
        with:
          phrase: 'skip-workflow'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        if: ${{ !steps.skip-workflow.outputs.skip }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format (Auto-fix)
        run: terraform fmt -recursive

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        if: ${{ !steps.skip-workflow.outputs.skip }}
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  # Estágio 3: Manual Approval
  manual-approval:
    name: Manual Approval Before Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: johnnymaxm
          issue-title: "Aprovação Manual para Terraform Apply"
          issue-body: "Por favor, revise o Terraform Plan e aprove para continuar com o Apply."
          exclude-approver: false
          minimum-approvals: 1

  # Estágio 4: Terraform Apply
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: manual-approval
    defaults:
      run:
        working-directory: terraform-checkov

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve