name: "Checkov Terraform Security Scan"

on:
  push:
    branches: [ "checkov" ]
  workflow_dispatch:

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  checkov:
    runs-on: ubuntu-latest
    name: checkov-terraform
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true
          soft_fail: true
          framework: terraform
          output_format: sarif
          output_file_path: reports/results.sarif
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: reports/results.sarif
          category: checkov-terraform
