name: Build and Push Docker image to ECR

on:
  push:
    branches: [ terraform ]

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 637423276160
  ECR_REPOSITORY: workflow
  IMAGE_TAG: build-${{ github.run_number }}
  ECR_URI: 637423276160.dkr.ecr.us-east-1.amazonaws.com/workflow

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t meuapache:${{ env.IMAGE_TAG }} .

  push-to-ecr:
    name: Push para AWS ECR
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login no ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS \
              --password-stdin $ECR_URI

      - name: Tag e Push da imagem
        run: |
          docker tag MeuApache:${IMAGE_TAG} $ECR_URI:${IMAGE_TAG}
          docker push $ECR_URI:${IMAGE_TAG}